apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dws-ingress
  namespace: dws
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod   # ðŸ”¹ Reference staging ClusterIssuer
spec:
  tls:
  - hosts:
    - dws.qatalyst.tech   # ðŸ”¹ Replace with your domain
    secretName: staging-tls # ðŸ”¹ Secret will be created automatically
  rules:
  - host: dws.qatalyst.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      
