apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dws-ingress
  namespace: dws
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod   # ðŸ”¹ Reference staging ClusterIssuer
spec:
  tls:
  - hosts:
    - apps.digitalqatalyst.com   # ðŸ”¹ Replace with your domain
    secretName: dws-tls # ðŸ”¹ Secret will be created automatically
  rules:
  - host: apps.digitalqatalyst.com
    http:
      paths:
      - path: /dws
        pathType: Prefix
        backend:
          service:
            name: dws-service
            port:
              number: 80
      