apiVersion: v1
kind: Secret
metadata:
  name: dws-secret
type: Opaque
stringData:
  VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptaHRyZmZteGp4aG94cGVzdWJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NzY3MjQsImV4cCI6MjA3ODA1MjcyNH0.LBQJNajOc8bWMt1Q_fj0Z_-fisUngLRrw2VSN-xrtR8"